### ISSUE TITLE
Lombok support

### ISSUE THREAD

**Issue by Paktosan** [sbt-compiler-maven-plugin/sbt-compiler-maven-plugin#41]
Hello,
I am using sbt-compiler-maven-plugin 1.0.0 as part of the play2-maven-plugin  to compile my code. I am also using the Lombok annotation `@Data`. I added Lombok by adding this to my pom.xml the way it is described here: https://projectlombok.org/mavenrepo/
But when I now build my project I get the following errors while building: https://gist.github.com/Paktosan/594339716d59946cc98cd4928df53dae
As you can see, it is complaining about not being able to find any of the Getters of my User model. But they should be there because I annotated the class with `@Data`.
Can you help me with that issue?

**Comment by gslowikowski** [comment]
Checkout and build locally (`mvn install`) `compile-order` branch of this plugin.

Change plugin version to `1.1.0-SNAPSHOT` in your project and set compile order to `JavaThenScala`:
```
    </properties>
...
        <sbt-compiler.plugin.version>1.1.0-SNAPSHOT</sbt-compiler.plugin.version>
    </properties>
...
            <plugin>
                <groupId>com.google.code.sbt-compiler-maven-plugin</groupId>
                <artifactId>sbt-compiler-maven-plugin</artifactId>
                <version>${sbt-compiler.plugin.version}</version>
                <configuration>
                    <compileOrder>JavaThenScala</compileOrder>
                </configuration>
            </plugin>
...
```

Tell me, if it helped.

**Comment by Paktosan** [comment]
Using the new version it throws different errors instead: https://gist.github.com/Paktosan/e6ee0c777c1ddb4306ac568c67db85ee

**Comment by gslowikowski** [comment]
Sorry for delay.

It will not work this way because in Play! project Java classes depend on Scala classes and vice versa. I forgot about it.

Read javadoc comments in the [CompileOrder](http://www.scala-sbt.org/0.13/sxr/xsbti/compile/CompileOrder.java.html) enum source and you will know everything about possible compilation orders.

When Scala compiler parses Java sources in mixed mode, it doesn't know, what methods will be added to Java class files during Java compilation later thanks to Lombok annotations.
This is the problem. I don't know, how to work around it. You can always ask a question on Stack Overflow.

**Comment by gslowikowski** [comment]
Found this on Stack Overflow:
https://stackoverflow.com/questions/11062167/lombok-with-play-2

**Comment by Paktosan** [comment]
I was hoping to be able to avoid creating a sub-project however it looks like I have to go that way until I figure out something better. Thanks for your help!

**Comment by gslowikowski** [comment]
Let me know if you find something.
